[package]
edition = "2021"
name = "aoc"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "aoc"

[dependencies]
pyo3 = "0.23.1"
rayon = "1.10.0"
thread_local = "1.1.8"
