[package]
name = "aoc2024-7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aoc2024_7"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
